# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Stylist' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Stylist
pod 'FirebaseAuth'
pod 'FirebaseStorage'
pod 'FirebaseFirestore'
pod 'FirebaseCore'
pod 'Toucan'
pod 'Kingfisher'
pod 'Cosmos'
pod 'Stripe'
pod 'Charts'
end
